# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/memories/imem_blk_ram/imem_blk_ram.xci
# IP: The module: 'imem_blk_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/memories/imem_blk_ram/imem_blk_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_blk_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/memories/imem_blk_ram/imem_blk_ram.xci
# IP: The module: 'imem_blk_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/memories/imem_blk_ram/imem_blk_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_blk_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
