# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/rgb2dvi_0.xci
# IP: The module: 'rgb2dvi_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/vivado_final/vivado_final.srcs/sources_1/ip/rgb2dvi_0/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'rgb2dvi_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
