# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/PYNQ-Z1_C.xdc

# IP: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/memories/imem_blk_ram/imem_blk_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==imem_blk_ram || ORIG_REF_NAME==imem_blk_ram} -quiet] -quiet

# IP: /home/cc/eecs151/sp18/class/eecs151-aar/sp18_team69/hardware/src/memories/dmem_blk_ram/dmem_blk_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==dmem_blk_ram || ORIG_REF_NAME==dmem_blk_ram} -quiet] -quiet
