# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/PYNQ-Z1_C.xdc

# IP: /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/memories/bios_mem/bios_mem.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bios_mem || ORIG_REF_NAME==bios_mem} -quiet] -quiet
