# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-17043-c125m-20.EECS.Berkeley.EDU/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7z020clg400-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src
    /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core
  } /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src
    /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core
  } {
      ./.Xil/Vivado-17043-c125m-20.EECS.Berkeley.EDU/realtime/imem_blk_ram_stub.v
      ./.Xil/Vivado-17043-c125m-20.EECS.Berkeley.EDU/realtime/dmem_blk_ram_stub.v
      ./.Xil/Vivado-17043-c125m-20.EECS.Berkeley.EDU/realtime/bios_mem_stub.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/button_parser.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/edge_detector.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/uart.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/uart_receiver.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/z1top.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/async_fifo.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/fifo.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/branch_control.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/reg_file.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/ALU.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/Riscv151.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/instruction_decoder.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/hazard_unit.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/control_unit.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/mem_read_decoder.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/audio/tone_generator.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/synchronizer.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/mem_control.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/uart_transmitter.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/io_circuits/debouncer.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/riscv_core/UART_controller.v
      /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/audio/i2s_controller.v
    }
      rt::read_vhdl -lib xpm /opt/Xilinx/Vivado/2017.4/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top z1top
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-17043-c125m-20.EECS.Berkeley.EDU/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] && [info exists rt::doParallel] && $rt::doParallel} { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
