# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/video/framebuffer_ram_1x786432/framebuffer_ram_1x786432/block_mem_1x786432.xci
# IP: The module: 'block_mem_1x786432' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/video/framebuffer_ram_1x786432/framebuffer_ram_1x786432/block_mem_1x786432_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem_1x786432'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/video/framebuffer_ram_1x786432/framebuffer_ram_1x786432/block_mem_1x786432.xci
# IP: The module: 'block_mem_1x786432' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/cc/eecs151/sp18/class/eecs151-aaq/sp18_team69/hardware/src/video/framebuffer_ram_1x786432/framebuffer_ram_1x786432/block_mem_1x786432_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'block_mem_1x786432'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
